# Final Model Comparison — Crop Disease Classification

This notebook reads the saved `*_results.json` files produced by each of the five
single-model notebooks (EfficientNetB3, DenseNet121, ResNet50, Xception, ConvNeXtTiny),
builds a comparison table, and selects the **top 3 models** for the next phase
(Confusion Matrix, ROC/AUC, Grad-CAM, SHAP/LIME, and other detailed analysis).

> Run this notebook only **after** all five model notebooks have finished training
> and each has saved its `RESULTS_DIR/<model>_results.json` file.

## 1. Import Libraries

In [1]:
import os
import glob
import json
import pandas as pd

## 2. Load Saved Results

In [6]:
RESULTS_ROOT = "Results"   # must match RESULTS_ROOT used in the model notebooks (Results/<MODEL_NAME>/)

result_files = glob.glob(os.path.join(RESULTS_ROOT, "*", "*_results.json"))
print(f"Found {len(result_files)} result file(s):")
for f in result_files:
    print(" -", f)

all_results = []
for file_path in result_files:
    with open(file_path, "r") as f:
        all_results.append(json.load(f))

Found 8 result file(s):
 - Results\ConvNeXtTiny\ConvNeXtTiny_results.json
 - Results\DenseNet121\DenseNet121_results.json
 - Results\EfficientNetB0\EfficientNetB0_results.json
 - Results\EfficientNetB3\EfficientNetB3_results.json
 - Results\InceptionV3\InceptionV3_results.json
 - Results\MobileNetV2\MobileNetV2_results.json
 - Results\ResNet50\ResNet50_results.json
 - Results\Xception\Xception_results.json

## 3. Build the Comparison Table

In [7]:
df = pd.DataFrame(all_results)

# Reorder / rename columns to match the required reporting format
df = df.rename(columns={
    "model": "Model",
    "train_accuracy": "Train Accuracy",
    "val_accuracy": "Validation Accuracy",
    "test_accuracy": "Test Accuracy",
    "precision": "Precision",
    "recall": "Recall",
    "f1_score": "F1-score",
    "test_loss": "Test Loss",
})[[
    "Model", "Train Accuracy", "Validation Accuracy", "Test Accuracy",
    "Precision", "Recall", "F1-score", "Test Loss",
]]

# Sort by Test Accuracy, highest to lowest
df_sorted = df.sort_values(by="Test Accuracy", ascending=False).reset_index(drop=True)
df_sorted

,Model,Train Accuracy,Validation Accuracy,Test Accuracy,Precision,Recall,F1-score,Test Loss
0,MobileNetV2,0.791975,0.814815,0.849817,0.855758,0.835071,0.841650,0.358264
1,DenseNet121,0.809926,0.829630,0.842491,0.838330,0.837471,0.837888,0.365858
2,EfficientNetB3,0.796199,0.777778,0.831502,0.840860,0.813141,0.820702,0.411972
3,InceptionV3,0.807814,0.814815,0.827839,0.840376,0.807514,0.815723,0.393274
4,ResNet50,0.805702,0.829630,0.827839,0.823740,0.821168,0.822347,0.382241
5,ConvNeXtTiny,0.820486,0.814815,0.824176,0.818993,0.820506,0.819703,0.342494
6,EfficientNetB0,0.809926,0.807407,0.824176,0.843254,0.800645,0.809822,0.412482
7,Xception,0.798310,0.740741,0.798535,0.811827,0.774909,0.782558,0.452182

## 4. Save the Comparison Table

In [8]:
comparison_path = os.path.join(RESULTS_ROOT, "final_model_comparison.csv")
df_sorted.to_csv(comparison_path, index=False)
print(f"Comparison table saved to: {comparison_path}")

Comparison table saved to: Results\final_model_comparison.csv

## 5. Select the Top 3 Models

These three models advance to the next phase: Confusion Matrix, ROC Curve, AUC, Grad-CAM, SHAP/LIME, and other detailed explainability analysis.

In [9]:
top3 = df_sorted.head(3)
print("Top 3 models selected for detailed analysis:")
top3

Top 3 models selected for detailed analysis:

,Model,Train Accuracy,Validation Accuracy,Test Accuracy,Precision,Recall,F1-score,Test Loss
0,MobileNetV2,0.791975,0.814815,0.849817,0.855758,0.835071,0.841650,0.358264
1,DenseNet121,0.809926,0.829630,0.842491,0.838330,0.837471,0.837888,0.365858
2,EfficientNetB3,0.796199,0.777778,0.831502,0.840860,0.813141,0.820702,0.411972